Fix layout inflation crash in compose flow
android.view.InflateException: Binary XML file line #32: Error inflating class ImageView
Caused by: android.content.res.Resources$NotFoundException: File res/color/compact_share_my_contacts_background_selector.xml from drawable resource ID #0x7f060076
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #3: <item> tag requires a 'drawable' attribute or child tag defining a drawable

This comment on Stack Overflow explains why this is happening and why
this change is necessary:
https://stackoverflow.com/questions/18913822/item-tag-requires-a-drawable-attribute#comment31621031_18915913