Fix crash due to mixing collapsed and non-collapsed counts
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.halloapp.ui.HeaderFooterAdapter.onCreateViewHolder(HeaderFooterAdapter.java:129)
        at com.halloapp.ui.home.HomeFragment.onCreateViewHolder(HomeFragment.java:633)