fix crash due to fragment detaching
java.lang.IllegalStateException: Fragment z{ba18c5} (b01c4ef5-4de8-40cd-a551-ed1b2cc52d75)} not attached to an activity.
       at androidx.fragment.app.Fragment.requireActivity(Fragment.java:833)
       at com.halloapp.ui.privacy.HideFuturePostsDialogFragment.lambda(HideFuturePostsDialogFragment.java:79)
       at com.halloapp.ui.privacy.-5127Lambda.onChanged(-.java:6)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)