Fix crash saving to gallery on API < 29
java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=3880, uid=10062 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
	[...]
        at com.halloapp.media.MediaUtils.saveMediaToGallery(MediaUtils.java:586)
        at com.halloapp.ui.mediaexplorer.MediaExplorerViewModel.lambda$savePostToGallery$1$MediaExplorerViewModel(MediaExplorerViewModel.java:155)